version: '3'

services:

   redis:
      image: redis
      hostname: redis
      networks:
         - app

   java:
      image: proundmega/http-app-local:1.0
      networks:
         - app
      depends_on:
         - redis
      deploy:
         mode: replicated
         replicas: 3
      ports:
         - 8080:8080/tcp

networks:
   app:
      driver: overlay
